### ISSUE TITLE
Problems with exporting images

### ISSUE THREAD

**Issue by sguldbra** [imperial-photonics/FLIMfit#143] opened 2015-06-15 12:54 UTC
Hi. I want to report a bug: When I try to export an image, the resolution is _very_ poor and the fontsize of the numbers on the scale bar are almost bigger than the image itself.

**Comment by imunro** [comment] 2015-06-26 15:46
@sguldbra I'm struggling to reproduce this. Do you have some data I could try with?

**Comment by seanwarren** [comment] 2016-04-26 10:20
Closing as unable to reproduce

**Closed by seanwarren** 2016-04-26 10:20 UTC
