### ISSUE TITLE
export data is showing NaN

### ISSUE THREAD

**Issue by Fredxxx** [imperial-photonics/FLIMfit#180] opened 2016-02-09 16:24 UTC
Sometimes when exporting data like histogramms or data from plotter menu some numbers are not shown as values but as NaN, even if they are included in the fit result table (export fit result table).

That is reducing the FLIMfit usability massively.

**Comment by Fredxxx** [comment] 2016-02-09 16:34
Sorry mixed the fit result tables up. The data isn't even shown in fit result table. Thus FLIMfit is not uasable at the moment................................

**Comment by seanwarren** [comment] 2016-02-09 19:15
Hi Fred, 

Can you give any more details about when this is happening? 

Cheers

**Comment by imunro** [comment] 2016-02-09 21:26
Hi Fred From what I saw the other day it looked as if this worked for most data ?

**Comment by Fredxxx** [comment] 2016-02-10 09:16
Hey Sean,

it is really suprising, refitting is not solving the issue. But if I close and start FLIMfit again it solved the issue. Thus the error is not really reproducable or I did something different the second time I load FLIMfit?! 
The attached files show data I meant with two different error behaviors. One is completly filled with NaN and the other one is just after a certain well filled with Nan.
[4nsCol11 tau_1 histogram.txt](https://github.com/imperial-photonics/FLIMfit/files/124430/4nsCol11.tau_1.histogram.txt)
[4ns_Column1 tau_1 histogram.txt](https://github.com/imperial-photonics/FLIMfit/files/124429/4ns_Column1.tau_1.histogram.txt)

Best
Frederik

**Comment by seanwarren** [comment] 2016-03-02 23:03
Hi I'm closing this as we can't reproduce - let me know if you see this again

**Closed by seanwarren** 2016-03-02 23:03 UTC
